"""
Strategy module for Polymarket US trading bot.

This module provides:
- BaseStrategy: Abstract base class for all trading strategies
- Signal: Immutable trading signal generated by strategies
- MarketMakerStrategy: Two-sided market making strategy
- StrategyEngine: Orchestration layer for managing strategies

Example:
    >>> from src.strategies import (
    ...     BaseStrategy,
    ...     Signal,
    ...     SignalAction,
    ...     Urgency,
    ...     MarketMakerStrategy,
    ...     MarketMakerConfig,
    ...     StrategyEngine,
    ... )
    >>> 
    >>> # Create engine with market maker
    >>> engine = StrategyEngine(state_manager, orderbook, executor)
    >>> engine.add_strategy(MarketMakerStrategy())
    >>> 
    >>> # Run the engine
    >>> await engine.run()
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .base_strategy import BaseStrategy, Signal, SignalAction, Urgency
    from .market_maker import MarketMakerConfig, MarketMakerStrategy, QuoteState
    from .strategy_engine import AggregatedSignals, SignalAggregator, StrategyEngine

__all__ = [
    # Base strategy
    "BaseStrategy",
    "Signal",
    "SignalAction",
    "Urgency",
    # Market maker
    "MarketMakerConfig",
    "MarketMakerStrategy",
    "QuoteState",
    # Strategy engine
    "AggregatedSignals",
    "SignalAggregator",
    "StrategyEngine",
]


def __getattr__(name: str) -> Any:
    """
    Lazy attribute loading to avoid import-time cycles.

    This keeps `from src.strategies import StrategyEngine` working while avoiding
    eager imports when other modules only need `src.strategies.base_strategy`.
    """
    if name in {"BaseStrategy", "Signal", "SignalAction", "Urgency"}:
        from .base_strategy import BaseStrategy, Signal, SignalAction, Urgency

        return {
            "BaseStrategy": BaseStrategy,
            "Signal": Signal,
            "SignalAction": SignalAction,
            "Urgency": Urgency,
        }[name]

    if name in {"MarketMakerConfig", "MarketMakerStrategy", "QuoteState"}:
        from .market_maker import MarketMakerConfig, MarketMakerStrategy, QuoteState

        return {
            "MarketMakerConfig": MarketMakerConfig,
            "MarketMakerStrategy": MarketMakerStrategy,
            "QuoteState": QuoteState,
        }[name]

    if name in {"AggregatedSignals", "SignalAggregator", "StrategyEngine"}:
        from .strategy_engine import AggregatedSignals, SignalAggregator, StrategyEngine

        return {
            "AggregatedSignals": AggregatedSignals,
            "SignalAggregator": SignalAggregator,
            "StrategyEngine": StrategyEngine,
        }[name]

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
